### ISSUE TITLE
[Bug]: Forcecraft fortune cookies disappear from hotbar momentarily

### ISSUE THREAD

**Issue by jporwave** [DarkPacks/SkyFactory-One#100]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.2

### Java version

14.0.2.0

### Modpack Launcher Used

CurseForge

### Memory Allocated

6.9

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

When eating a fortune cookie from Forcecraft with two or more in your hotbar, one will 'disappear' when the animation completes and your hotbar auto-fills it to the slot currently selected. I was able to make it reappear either after opening your inventory and clicking on the slot that was selected when eating the cookie, or by opening and closing the extra inventory from the ender inventory cake. Right clicking with the empty hotbar selected will also do nothing despite the other cookie technically now being there.

It's also possible to make more than one 'disappear' by having three or more cookies in your hotbar and eating more than one before forcing the previous one to reappear. As far as I can tell nothing is actually lost, just visually bugged.

### Additional Information

hard to show through screenshots but here's a before and after if it helps https://imgur.com/a/TIil2nH

**Comment by Darkosto** [comment]
Fixed in Forcecraft update. Will be available in the next pack update. Thanks!
