### ISSUE TITLE
[Bug]: cyclic fluid/item cable visual bug

### ISSUE THREAD

**Issue by jporwave** [DarkPacks/SkyFactory-One#102]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.2

### Java version

14.0.2.0

### Modpack Launcher Used

CurseForge

### Memory Allocated

6.9

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

Placing a cyclic cable between two other cables of the same kind (so that all three connect) creates a visually broken connection.
This happens with both fluid and item cables, but doesnt seem to affect energy cables.

You can use a wrench to cycle through the connections, or connect a chest/tank directly to one of the cables in order to fix it, but as far as I can tell the broken connection is purely visual.

### Additional Information

https://imgur.com/a/Z7C01lx

**Comment by Darkosto** [comment]
Fixed up in the newest Cyclic update, will be in the next modpack update. Thank you!
