### ISSUE TITLE
[Bug]: When opening the Hats menu the game crashed

### ISSUE THREAD

**Issue by Mitchninja88** [DarkPacks/SkyFactory-One#105]
### General Info

- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.2

### Java version

java version "1.8.0_271"

### Modpack Launcher Used

CurseForge

### Memory Allocated

8 GB

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

When I opened the hat's menu the game crashed. Happened after killing a sheep for a skyrim helmet.

### Additional Information

https://pastebin.com/Aqx7SLA9

**Comment by Darkosto** [comment]
I'm unable to replicate this one, if it happens again let me know and share the crash report please.
