### ISSUE TITLE
[Suggestion]: Add recommended RAM allocation to pack description

### ISSUE THREAD

**Issue by James103** [DarkPacks/SkyFactory-One#107]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

There is currently no way to get the recommended amount of RAM from within the pack description. All I see is that Java 15+ is not supported and that some people make issues and state that the RAM allocated is around 5 to 10 GB (most commonly 8 GB).

I need info on the RAM recommendation so that I can determine whether I can run the pack on my current computer with the current amount of RAM I have (8 GB total).

**Comment by Darkosto** [comment]
Just added a 4gb minimum recommendation to the Curseforge page
