### ISSUE TITLE
[Bug]: Recipe for Magma with Slimeball in the solidification chamber resulting in magma cream not working

### ISSUE THREAD

**Issue by Bingers69** [DarkPacks/SkyFactory-One#110]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Modpack version

1.0.2

### Java version

Java 8 Update 311

### Modpack Launcher Used

CurseForge Launcher

### Memory Allocated

12GB

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Server Java Version

Java 8 Update 311

### Server Operating System

Windows

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

Attempting to use the Cyclic solidification chamber to make magma cream. Using the recipe to melt down magma block and then use slimeballs to make magma cream. I transfer the melted magma to the solidification chamber and add either one or three slimeballs. The process countdown runs from 100-1 then stops and nothing happens. I restarted the pack and tried multiple times and not working.

**Comment by Darkosto** [comment]
This fix will be added in Cyclic. I'm waiting on the update to test and confirm it works. I'll hopefully have this ready for the next pack update (1.0.3)
