### ISSUE TITLE
[Bug]: water in container

### ISSUE THREAD

**Issue by EkutoruSama** [DarkPacks/SkyFactory-One#111]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I am using the latest version of the modpack

### Modpack version

1.0.2

### Java version

java 8 update 311

### Modpack Launcher Used

CurseForge Launcher

### Memory Allocated

4 GB

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Server Java Version

Java 8 update 311

### Server Operating System

Windows

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

When I look a container, the water desapear.

Juste a certain angle give a look at the water.

It´s probably the same with lava and every liqui
![2021-10-30_18 20 15](https://user-images.githubusercontent.com/77534573/139541295-b97692db-cd5a-48d1-866a-180da547eec3.png)
![2021-10-30_18 20 17](https://user-images.githubusercontent.com/77534573/139541301-d05fbef9-8ba6-41bb-97f0-5e13ab517af9.png)
ds

**Comment by willrun4fun** [comment]
Are you using Fabulous instead of Fancy in Video Settings?  Fabulous renders water differently and can cause this.

**Comment by Darkosto** [comment]
This looks like it's due to Fabulous graphics settings. I would suggest using Fancy since the benefit of Fabulous doesn't outweigh the issues. There really isn't much I can do from the modpack side of things since this would require all the mods involved to update to fix the problem
