### ISSUE TITLE
[Bug]: Crash 

### ISSUE THREAD

**Issue by CrevetteTV** [DarkPacks/SkyFactory-One#117]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.2

### Java version

1.8.0_51

### Modpack Launcher Used

Lanceur de CurseForge

### Memory Allocated

16

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

Hello I put an entangled loader in refined storage and I broke everything. I crash every time I start the game. sorry for the mistakes I am French

**Comment by Darkosto** [comment]
I can't investigate this issue without a crash report. Your best chance of fixing your world is to go into the defaultconfigs folder and locate the `forge-server.toml` file and change the following option to `true` 
```
	#Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
	removeErroringEntities = false
```

Then, start up the modpack and try to load your world. If it does not fix it, then you're next option would be to remove the entangled mod and then restart modpack and load the world. You can then go ahead and add the mod back in if this works.

**Comment by CrevetteTV** [comment]
Here is attached the crash report

[crash-2021-11-05_11.07.18-client.txt](https://github.com/DarkPacks/SkyFactory-One/files/7482254/crash-2021-11-05_11.07.18-client.txt)

**Comment by Darkosto** [comment]
Closing this as there has been no response
