### ISSUE TITLE
[Suggestion]: 

### ISSUE THREAD

**Issue by EGDIRBMA** [DarkPacks/SkyFactory-One#119]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

any offical or trusted servers post here for publicity. (p.s. im looking for a new home)

**Comment by sam-kirby** [comment]
There are no official or trusted servers.

You can use the channel #sf-multiplayer-ads on the Discord server https://discord.gg/darkosto to try and connect with server operators.
