### ISSUE TITLE
[Suggestion]: Add bamboo so it's compostable in the barrels

### ISSUE THREAD

**Issue by BigAl607** [DarkPacks/SkyFactory-One#124]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Would like to add bamboo to the barrels to compost into dirt. IMO, once you have a stack+ of scaffolding, there's no real use for it.

**Comment by Darkosto** [comment]
Will add in the next pack update. For now you can throw this into the following datapack folder: 

`.minecraft\global_data_packs\skyfactoryone\data\sf_one\recipes\compostable`


create a new file called `bamboo_compost.json`

and insert this: 

```json
{
  "type": "exnihilosequentia:compost",
  "input": {
    "item": "minecraft:bamboo"
  },
  "amount": 20
}
```

**Comment by BigAl607** [comment]
Works great!
