### ISSUE TITLE
[Bug]: Beheading Enchantment drops mob heads that exclude certain recipes

### ISSUE THREAD

**Issue by TrickyEagle** [DarkPacks/SkyFactory-One#126]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.2

### Java version

1.8.0_301

### Modpack Launcher Used

MultiMC

### Memory Allocated

8 GB

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

When using a vanilla Minecraft sword enchanted with the enchantment "beheading" any mob drop head comes with the title "MHF_(insertmobheadnamehere)". For example, killing a blaze with the above-enchanted sword drops a blaze head that cannot be melted in a smeltery or anything.

**Comment by Darkosto** [comment]
Added this to the Cyclic tracker as a compatibility suggestion: https://github.com/Lothrazar/Cyclic/issues/1966

**Comment by Darkosto** [comment]
Cyclic has updated and this is now resolved. Will be out with the new pack update. Thanks!
