### ISSUE TITLE
[Suggestion]: Update Pipez Mod

### ISSUE THREAD

**Issue by heinrich26** [DarkPacks/SkyFactory-One#133]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Id like to suggest updating the pipez mod, because in the latest release, a bug where the filters do add the damage tag, whenever you want to filter for enchanted items :)

Thanks, heinrich27

**Comment by Darkosto** [comment]
Updated for the next pack release
