### ISSUE TITLE
[Bug]: Cyclic "Vision Helmet" doesn't work in additional head slot

### ISSUE THREAD

**Issue by Zizes** [DarkPacks/SkyFactory-One#134]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.2

### Java version

Java 8 Update 311

### Modpack Launcher Used

CurseForge Launcher

### Memory Allocated

30 GB

### Minecraft World Environment

LAN

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Server Java Version

Java 8 Update 311

### Server Operating System

Windows

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

The "Vision Helmet" doesn't give "Night Vision" if I put it in **_additional_** head slot that is allowed.  (As I understand it is "Curios" mod inventory slot) 
If I put this helmet in default head armor slot it works correctly.

P.S.:
I couldn't find any crash report for this problem.

**Comment by Darkosto** [comment]
This sounds like the mod is working as the developer intended. If you feel this should be added then you should put a ticket into the Cyclic tracker since I cannot control this.
