### ISSUE TITLE
[Bug]: Loading default world type, not loading sky world

### ISSUE THREAD

**Issue by sewHappyMC** [DarkPacks/SkyFactory-One#14]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

Release Candidate

### Java version

Java JDK 16.0.2

### Modpack Launcher Used

MultiMC 5

### Memory Allocated

8GB

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

Single Player, Allow cheats, Create New World. Default MC world loads not sky world. Tested on Curse with same steps and it loads Sky World (on the tree). If I go into the more world options screen any of the world types with a customize button will not open a menu when the customize button is clicked. Also the only option for typography is World Type: generator.topography

### Additional Information
![Capture](https://user-images.githubusercontent.com/88454474/136603624-8299f105-84bf-43ec-b328-064d87aca40e.PNG)

**Comment by Darkosto** [comment]
Java 16 is not supported for 1.16.5, please downgrade to 8, 11, or 14. Do not go past those versions. Forge officially supports Java 8 for 1.16
