### ISSUE TITLE
[Suggestion]: Make heads we get using beheading enchantment work with tinkers recipes

### ISSUE THREAD

**Issue by ivxvm** [DarkPacks/SkyFactory-One#142]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

I have a Supremium Sword with Beheading IV and the heads I get from blazes are called "MHF_Blaze's Head" (itemid is minecraft:player_head). Unfortunately they don't work in melting recipe for Blazing Blood (recipe expects tconstruct:blaze_head).

**Comment by sam-kirby** [comment]
This is a duplicate of #126
