### ISSUE TITLE
[Suggestion]: Topoisland Permission

### ISSUE THREAD

**Issue by djburg** [DarkPacks/SkyFactory-One#143]
### General Info

- [X] I would like to propose new content
- [X] I would like to propose changes
- [x] I would like to propose another thing

### Suggestion Description

I've been waiting for this project. Would it be possible to get topoisland permissions? Would it be possible to get island protection?

**Comment by Darkosto** [comment]
I'm not understanding what you mean. Could you help me understand what you are asking for?

**Comment by djburg** [comment]
Cancel Issue
