### ISSUE TITLE
[Bug]: AutoHammer, AutoCompressedHammer, AutoCompressedSieve, AutoCompressor and AutoSieve recipes missing from JEI

### ISSUE THREAD

**Issue by metalshark** [DarkPacks/SkyFactory-One#146]
### General Info

- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.2

### Java version

Azul Zulu 8u312b07 8.58.0.13

### Modpack Launcher Used

Minecraft Launcher App Store Version

### Memory Allocated

16GB

### Minecraft World Environment

Server

### Misc Client Info

- [X] Optifine Installed
- [X] Shaders Installed

### Server Java Version

1.8.0_201

### Server Operating System

Linux (amd64) version 5.4.0-65-generic

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

AutoHammer, AutoCompressedHammer, AutoCompressedSieve, AutoCompressor and AutoSieve recipes are missing from JEI. Is this due to a conflict between ExCompressum's recipes and ExNihiloSequentia's?

**Comment by sam-kirby** [comment]
No; they are deliberately hidden from JEI through the blacklist:

https://github.com/DarkPacks/SkyFactory-One/blob/main/src/config/jei/blacklist.cfg#L348-L352

Even if they weren't hidden, the recipes for them are disabled:

https://github.com/DarkPacks/SkyFactory-One/blob/main/src/global_data_packs/skyfactoryone/data/excompressum/recipes/auto_hammer.json

**Comment by metalshark** [comment]
Fair enough - although I cannot see the recipes coming through from ExNihiloSequentia in JEI yet you can craft them.

**Comment by metalshark** [comment]
Have just been informed by the server admin they enabled them. Apologies.
