### ISSUE TITLE
[Bug]: Chance Cube Water in the Nether

### ISSUE THREAD

**Issue by Shadow-player** [DarkPacks/SkyFactory-One#148]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.3

### Java version

java 8 311

### Modpack Launcher Used

Overwolf

### Memory Allocated

8 GB

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

Not sure if this is even a bug...
(I got this twice from chance cubes, so it wasn't a one off)

Chance cubes can create water in the nether.
You can fill buckets, but not place it down anywhere other than where the cube created a source block.

![2021-11-27_21 33 34](https://user-images.githubusercontent.com/10368824/143731016-2127bee8-f06e-4379-b94d-d8ac6e255b59.png)

**Comment by TheTurkeyDev** [comment]
Nothing really to be done about this. CC used to have a way to disable rewards in certain dimensions, but it was complicated, caused bugs, and no one used it. This is just one of those things where if you use the mod, this is something that can happen ¯\_(ツ)_/¯

**Comment by Darkosto** [comment]
Haha, this is great. Seems like a fun feature!
