### ISSUE TITLE
[Bug]: Blast Furnace gives out wrong ingots

### ISSUE THREAD

**Issue by Kobra652** [DarkPacks/SkyFactory-One#150]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.3

### Java version

Java 8

### Modpack Launcher Used

Curseforge

### Memory Allocated

10

### Minecraft World Environment

Single Player

### Misc Client Info

- [X] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

When I put modded ore chunks from Ex Nihilo in the vanilla blast furnace, it produces ingots from Ex Nihilo instead of Thermal. The Ex Nihilo ingots can't be used for crafting at all. I'm guessing this was an oversight when altering the recipes.

**Comment by Darkosto** [comment]
Oh whoops, forgot the blast furnace has its own set of recipes. Will be fixed in the next version
