### ISSUE TITLE
[Bug]: 1.0.4 Server settings.bat needs version updated

### ISSUE THREAD

**Issue by tuckerliv** [DarkPacks/SkyFactory-One#153]
### General Info

- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Modpack version

1.0.4

### Java version

1.8.0_311

### Modpack Launcher Used

Server Pack downloaded from CurseForge

### Memory Allocated

8 GB

### Minecraft World Environment

Server

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Server Java Version

1.8.0_311

### Server Operating System

Windows

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

Fresh download as of about 7:30 PM Central on 12/12 from Curse Forge of the 1.0.4 server pack.  The settings.bat file still references forge-1.16.5-36.2.19 instead of .20 for both the INSTALL_JAR and the SERVER_JAR.    The file modified date for settings.bat shows 12/1/2021 in the .zip too. I checked the settings.sh file and it has been updated. I copied the values out of that and everything looks good.  Thanks for the hard work on addressing the vulnerability!

default
set INSTALL_JAR=forge-1.16.5-36.2.19-installer.jar
set SERVER_JAR=forge-1.16.5-36.2.19.jar

My update
set INSTALL_JAR=forge-1.16.5-36.2.20-installer.jar
set SERVER_JAR=forge-1.16.5-36.2.20.jar

### Additional Information

Error on initial server start up was:
C:\Users\tuckerliv\Downloads\SkyFactory_One_Server_1_0_4>ServerStart.bat
Checking Java
Java Installed: "1.8.0_311"
Starting SkyFactory One Server...
Error: Unable to access jarfile forge-1.16.5-36.2.20.jar
Press any key to continue . . .

Install.bat did not give errors, but completed immediately
C:\Users\tuckerliv\Downloads\SkyFactory_One_Server_1_0_4>Install.bat
Installing Forge and required jars.
Press any key to continue . . .

**Comment by artdude543** [comment]
This has now been resolved in an update to the server files. [Download](https://www.curseforge.com/minecraft/modpacks/skyfactory-one/files/3576695)
