### ISSUE TITLE
[Bug]:  CC:Tweeks Printer placed in world next to computer Crashed game. Not able to load now

### ISSUE THREAD

**Issue by StompEm** [DarkPacks/SkyFactory-One#154]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.4

### Java version

current

### Modpack Launcher Used

CurseForge

### Memory Allocated

6 GB

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

Printer crashed game, not able to load world now

**Comment by MattiDragon** [comment]
Update: Updating to the latest CC seems to have fixed it

**Comment by MattiDragon** [comment]
Or I broke something else the computer seems broken

**Comment by MattiDragon** [comment]
Ok, so it seems I just broke it even more with updating. Possibly could have missed some setup, but seems to be broken

**Comment by sam-kirby** [comment]
Fixed in 1.0.5
