### ISSUE TITLE
[Bug]: world generates incorrectly, uses normal world generation

### ISSUE THREAD

**Issue by triplrrr** [DarkPacks/SkyFactory-One#158]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.4

### Java version

Java 8 update 311

### Modpack Launcher Used

MultiMC

### Memory Allocated

8 GB

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

i created the world and i ended up in a normal world, not a skyblock world like i expected. i then reinstalled the pack and got the same result. i attempted to use the topography world option but that spawned me in a void world where i continually died. 

i believe the issue is the same as #83, especially since i never saw a real solution posted there. I plan on testing with different java versions (11 and 14) to ensure that it is not related to that. 

### Additional Information

[log](https://gist.github.com/triplrrr/8fa095af063b34d863c65cb0b92a33bc)

**Comment by sam-kirby** [comment]
> Java is version 17.0.1

You are not using Java 8

Please use a supported version of Java.

**Comment by triplrrr** [comment]
@sam-kirby 

from [the curseforge page for the pack](https://www.curseforge.com/minecraft/modpacks/skyfactory-one)

> Please note: Java 16 is not supported in this modpack for clients or servers. You can use Java 8, 11, and 14.

i am using the latest version of java 8 as far as i know

**Comment by sam-kirby** [comment]
@triplrrr 

I was clearly in a rush when I responded to you and did not provide enough context. The quoted line is from your log, line 28 to be exact. It's confirmed by the game on line 240:

> java version 17.0.1 by Oracle Corporation

If you are experiencing this issue whilst using Java 8 then you need to provide a log that supports this. Your log shows you are using Java 17 which is unsupported.

In MultiMC you can override the version of Java used in the "Edit Instance" window, or in the main "Settings" window.

**Comment by triplrrr** [comment]
Ah, I apologize then. I thought i had configured the instance to use java 8 but it seems i was mistaken. thanks for your help.
