### ISSUE TITLE
[Bug]: Item dupe

### ISSUE THREAD

**Issue by superfishy07** [DarkPacks/SkyFactory-One#159]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.4

### Java version

Java 1.8.0 312

### Modpack Launcher Used

GDlauncher

### Memory Allocated

4GB

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Server Operating System

Windows (Bisect Hosting server)

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

If you try and craft more of an item than your inventory can hold, the source item gets duplicated.
In the screen shots, I'm crafting logs into planks. My action is to shift click the planks into my inventory.  What I assume would happen is only enough logs get crafted into planks as my inventory can hold.

What actually happens is the stack of 2 planks in my inventory is made a full stack, and I'm left with 20 logs in the crafting table, plus 2 planks, and I'm suddenly holding a stone block.

Just before shift clicking
![MC_bug1](https://user-images.githubusercontent.com/50976201/148497112-9996caad-b5c3-4f61-988d-cc8bfc788085.PNG)

Just after shift-clicking
![MC_bug2](https://user-images.githubusercontent.com/50976201/148497139-ed5510dd-1430-4282-88e7-e81a5e569658.PNG)

The server console doesn't show anything strange having happened.

**Comment by linktlh** [comment]
This dupe bug is relating directly to FastWorkBench and solved in fde6d212cde0b43d864618c0a24a8fc7e199998d . An update in the mod would remedy this bug.

**Comment by wasdcu** [comment]
when using this mod with a full inventory the items multiply to infinity
![2022-04-19_17 45 51](https://user-images.githubusercontent.com/96142999/164093996-f2c443c2-1b68-4c6f-835d-ac4695bd1b56.png)
shift+click
![2022-04-19_17 45 56](https://user-images.githubusercontent.com/96142999/164094100-c202061b-c63e-450f-bfa1-d662631299d7.png)
.some craftings already multiply the bug many times
![2022-04-19_17 36 28](https://user-images.githubusercontent.com/96142999/164094244-a3e7fc04-4806-40a2-b7d4-6718e05df5f2.png)
![2022-04-19_17 35 23](https://user-images.githubusercontent.com/96142999/164094249-c20f633a-7442-45a4-ac89-8554c4aa1341.png)

**Comment by sam-kirby** [comment]
This has been fixed; update to 1.0.5.
