### ISSUE TITLE
[Bug]: Placing down a CC computer next to a some blocks crash the game

### ISSUE THREAD

**Issue by MattiDragon** [DarkPacks/SkyFactory-One#163]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.4

### Java version

Vanilla Launcher Bundled

### Modpack Launcher Used

CurseForge Launcher

### Memory Allocated

4 GB

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

When I place down a computercraft computer next to some blocks it immediately crashes the game. These blocks include, but are probably not limited to other computers and chests from the iron chests mod. It crashes again when I restart and reopen the world.  It is probably an internal CC issue, but might be something you can work around.

### Additional Information

Crash Report: https://pastebin.com/jbhbFEnH

**Comment by jswalhop** [comment]
Hi, is there any fix for this yet? I just did it on my dedicated server and I have no backups.


[crash-2022-02-04_14.58.18-server.txt](https://github.com/DarkPacks/SkyFactory-One/files/8004078/crash-2022-02-04_14.58.18-server.txt)
.

**Comment by MattiDragon** [comment]
> Hi, is there any fix for this yet? I just did it on my dedicated server and I have no backups.
> 
> 
> [crash-2022-02-04_14.58.18-server.txt](https://github.com/DarkPacks/SkyFactory-One/files/8004078/crash-2022-02-04_14.58.18-server.txt)
> .

You can manually edit the region file to replace the block in the chunk with air. It's a pain, but works. Alternatively you can delete the chunk.

**Comment by jswalhop** [comment]
Thanks. I will try this now.

**Comment by jswalhop** [comment]
Is there a way to find where i was before i disconnected?

**Comment by MattiDragon** [comment]
Seems to be fixed in 1.0.5
