### ISSUE TITLE
[Bug]: Server crash on start

### ISSUE THREAD

**Issue by jjamesk** [DarkPacks/SkyFactory-One#164]
### General Info

- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

SkyFactory One - 1.0.4

### Java version

java version "17.0.1" 2021-10-19 LTS

### Modpack Launcher Used

Curse Forge

### Memory Allocated

8 GB

### Minecraft World Environment

Server

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Server Java Version

openjdk 11.0.14 2022-01-18

### Server Operating System

Linux

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

Server version crashes on start

Server Details:
OS: Debian 11
Java: openjdk 11.0.14 2022-01-18
Server Type: dedicated hardware, no a VPS
Server CPU: 12 Cores 
Server RAM: 64GB

[15Feb2022 08:19:55.059] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
[debug.log](https://github.com/DarkPacks/SkyFactory-One/files/8066760/debug.log)
[latest.log](https://github.com/DarkPacks/SkyFactory-One/files/8066761/latest.log)

Logs attached

**Comment by sam-kirby** [comment]
A recent change in Java broke the version of modlauncher (a component of Forge) included with the pack. The latest versions of Java 8 and 11 are affected.

The most sure way of making it work for you at the moment is to downgrade Java, although updating Forge is also an option - though you may run into other issues.

The long term solution is for the maintainers of this pack to update Forge.

**Comment by sam-kirby** [comment]
See: McModLauncher/modlauncher#91

**Comment by sam-kirby** [comment]
This should be resolved in 1.0.5
