### ISSUE TITLE
[Suggestion]: Server Close when i close putty

### ISSUE THREAD

**Issue by K3ks125** [DarkPacks/SkyFactory-One#165]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

[Suggestion]: Server Close when i close putty

**Comment by sam-kirby** [comment]
Closing PuTTY is equivalent to logging out; all your programs are closed.

There are numerous ways to get around this, however. The simplest is to use `screen` or `tmux`, but other options include making the server a system service or disowning the server process once started.

If you need further help, please ask on Discord: https://discord.gg/darkosto
