### ISSUE TITLE
[Bug]: CC: tweaked disk drive crash.

### ISSUE THREAD

**Issue by CaptCaboose** [DarkPacks/SkyFactory-One#168]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.4

### Java version

Java 8 update 311 (64-bit)

### Modpack Launcher Used

MultiMC

### Memory Allocated

16gb

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

Placing down a disk drive in my world caused it to crash repeatedly. Recommended fix is to update supplementals and cc tweaked.

**Comment by sam-kirby** [comment]
Issue is fixed in 1.0.5, please update.
