### ISSUE TITLE
[Suggestion]: add Auto Sieve

### ISSUE THREAD

**Issue by arshiahaeri89** [DarkPacks/SkyFactory-One#169]
### General Info

- [X] I would like to propose new content
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Now we use click machine for automatically siving. But There is a mod that has auto siving with power.

**Comment by sam-kirby** [comment]
> SkyFactory® One is a modernization of the original SkyFactory for Minecraft 1.6.4. The goal of this project is to remain true to the original modpack

This would run counter to the packs aims.
