### ISSUE TITLE
[Bug]: Water placed onto a slab clips through the bottom and doesn't flow correctly

### ISSUE THREAD

**Issue by abryzak** [DarkPacks/SkyFactory-One#17]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.0-rc.5

### Java version

jre1.8.0_281

### Modpack Launcher Used

MultiMC

### Memory Allocated

8GB

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

When placing a bucket of water onto a slab, it clips into the slab instead of placing the water on top of the slab. 

This also prevents the water from spreading correctly, if trying to make an infinite water source with a 2x2 grid on top of slabs.

### Additional Information

![2021-10-09_23 49 55](https://user-images.githubusercontent.com/271604/136661077-df7d4f75-1ba6-4cf6-a17a-897f41c306d0.png)
![2021-10-09_23 57 23](https://user-images.githubusercontent.com/271604/136661079-27645e7c-2b18-4935-83fc-1583bf094379.png)
![2021-10-09_23 56 24](https://user-images.githubusercontent.com/271604/136661088-483ae3c3-6bda-4ca9-8a23-441db097e4d0.png)

**Comment by Darkosto** [comment]
This is how the vanilla waterlogged mechanic works, it's not a bug it's intended behavior. This was added a few major updates ago. Nothing in the modpack is altering the vanilla behavior
