### ISSUE TITLE
[Bug]: click machine breaks the grinder handle

### ISSUE THREAD

**Issue by arshiahaeri89** [DarkPacks/SkyFactory-One#170]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.5

### Java version

Java 8 update 291

### Modpack Launcher Used

TLauncher

### Memory Allocated

4GB

### Minecraft World Environment

Single Player

### Misc Client Info

- [X] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

I am using click machine for rotating grinder handle but when grinder is empty grinder handle broken.

**Comment by arshiahaeri89** [comment]
And click machine always is right clicking

**Comment by sam-kirby** [comment]
Working as intended.
