### ISSUE TITLE
[Bug]: CC: Tweaked Turtle Crash

### ISSUE THREAD

**Issue by MagnaStone77** [DarkPacks/SkyFactory-One#175]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.4

### Java version

Java 8 Update 51

### Modpack Launcher Used

CurseForge Launcher

### Memory Allocated

4 GB

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

Whenever I place a CC: Tweaked turtle that is not the base turtle (like Wireless Turtle and Crafty Turtle), as far as I can tell, the game crashes and the world is no longer able to be opened. When I try to reload the world the world loading screen comes up and loads, but as soon as it reaches 100% and tries to place me in the world, I crash. This is similar to another crash report I saw, but not exactly the same as it happens whenever I place a turtle anywhere, even in a newly created world.

### Additional Information

Crash Report:
[https://pastebin.com/ewydUmTE](url)

**Comment by sam-kirby** [comment]
You are not using the latest version of the modpack; this is fixed in 1.0.5
