### ISSUE TITLE
[Bug]: Game Instance Crashes on Startup

### ISSUE THREAD

**Issue by RC-Neko** [DarkPacks/SkyFactory-One#177]
### General Info

- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.4

### Java version

Java 8 Update 341

### Modpack Launcher Used

MultiMC

### Memory Allocated

min. 4GB max 8GB

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

Expected Behavior:
Game initializes normally.

Real Behavior:
Game initializes for about ~3 seconds and then crashes

Steps to reproduce:
Press Launch and wait

### Additional Information

Link to Crash Reports:
https://paste.ee/p/s0g3c

Client before it crashes:
![mrVEcQ3Qco](https://user-images.githubusercontent.com/111229690/184536613-7f37a880-2b32-438d-b6d9-3d0f80f9ae41.png)
Workarounds Settings:
![MultiMC_7mI07RUqXe](https://user-images.githubusercontent.com/111229690/184536481-641d10be-e75e-4989-9d32-16e9c30ab708.png)

Java Installation Settings 1:
![MultiMC_7UNnqjzFpO](https://user-images.githubusercontent.com/111229690/184536482-ab8e3c74-d870-4038-af85-99bcde731c57.png)

Java Installation Settings 2:
![MultiMC_F9gXvkSW9A](https://user-images.githubusercontent.com/111229690/184536487-6f949673-ab20-42d0-9c18-b4b96fa0e3d1.png)

Game Window Settings:
![MultiMC_bcZa5DOXg5](https://user-images.githubusercontent.com/111229690/184536483-0bcff0e2-15e0-432b-8903-dbc0b9377555.png)

Misc Settings:
![MultiMC_cgrD9H5wcY](https://user-images.githubusercontent.com/111229690/184536485-2efb75d6-979a-452a-830d-743343a95df3.png)

Custom Command Settings:
![MultiMC_mhivFa4PK4](https://user-images.githubusercontent.com/111229690/184536488-22505d0c-fa74-419c-916f-d86b9670ad6d.png)

**Comment by artdude543** [comment]
This isn't a bug but a setup issue. Minecraft 1.16 does not support Java 8. You need at-least Java 14+ but no more than 17. You can find a guide on how to download and set up the Java for MultiMC below.

https://github.com/Preocts/darko_java_help/blob/source/README.md#openjdk-14-for-default-launcher-or-multimc

Once you've installed the correct Java and changed the Java on MultiMC you'll be crash free.

Any issues please feel free to comment.

**Comment by sam-kirby** [comment]
Hi, the above response is incorrect. Your version of Java is fine provided you update the pack to 1.0.5. Do not use a version of Java later than 14 with this pack.

**Comment by RC-Neko** [comment]
Thank you for your help. I re-downloaded the newer version, its working now.
