### ISSUE TITLE
[Bug]: On server ex compressum won't load

### ISSUE THREAD

**Issue by Lunass** [DarkPacks/SkyFactory-One#187]
### General Info

- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.5

### Java version

version 8 update 391

### Modpack Launcher Used

prism launcher

### Memory Allocated

8 gb

### Minecraft World Environment

Server

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Server Java Version

unsure, the site doesn't seem to say

### Server Operating System

linux

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

server isn't loading ex compressum, I looked this up, and it seems to be a known issue, but it only happens on my server and not in singleplayer, I checked the version of ex compressum, and they both use the latest version, so I'm not sure why it only errors on the server

### Additional Information

19.12 18:53:27 [Server] Thread-4/ERROR [excompressum/]: Could not load remote skins for auto sieve: 
server gives this error when loading, and doesn't have ex compressum

**Comment by sam-kirby** [comment]
Not a bug; most of Ex Compressum is intentionally disabled as this is a faithful recreation of SF1, where these items were not available.

It sounds like your client isn't setup properly, or maybe you disabled the datapack.

To renable, you would need to turn their recipes back on, e.g. by removing the files that disable them; for example for compressed dirt remove https://github.com/DarkPacks/SkyFactory-One/blob/main/src/global_data_packs/skyfactoryone/data/excompressum/recipes/compressed_dirt.json

You may also want to unhide the items in JEI by removing them from the blacklist here https://github.com/DarkPacks/SkyFactory-One/blob/main/src/config/jei/blacklist.cfg#L329
