### ISSUE TITLE
[Server Files]: Information Missing

### ISSUE THREAD

**Issue by Gremkow** [DarkPacks/SkyFactory-One#20]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I am using the latest version of the modpack

### Modpack version

1.0.0

### Java version

-

### Modpack Launcher Used

-

### Memory Allocated

-

### Minecraft World Environment

Server

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Server Java Version

-

### Server Operating System

Debian

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

The README.txt seems to be missing some information:

"NOTE: If you are using Java 14 or above. Please edit the settings file to remove"

It is missing what needs to be removed.

**Comment by artdude543** [comment]
Ha! I should never make edits while on a massive lack of sleep! Will resolve for when we push the next update.

The item should read as followed upon that being pushed.

```
NOTE: If you are using Java 14 or above. Please edit the settings file to remove all the "JAVA_PARAMETERS" so then it's an empty string I.E. ""
On Windows you'll need to edit the settings.bat on Linux/Mac you'll need to edit settings.sh.
```

**Comment by justinrusso** [comment]
> Ha! I should never make edits while on a massive lack of sleep! Will resolve for when we push the next update.
> 
> The item should read as followed upon that being pushed.
> 
> ```
> NOTE: If you are using Java 14 or above. Please edit the settings file to remove all the "JAVA_PARAMETERS" so then it's an empty string I.E. ""
> On Windows you'll need to edit the settings.bat on Linux/Mac you'll need to edit settings.sh.
> ```

@artdude543 I don't think the pack supports anything above 14. From my understanding, Topography will have problems with anything above. Not sure the best way we can provide that information to users, but we should at least update that file to state so.

**Comment by Darkosto** [comment]
A warning has been added to the pack description pages to not use Java 16. The information will also be added to the server setup files in pack version 1.0.1
