### ISSUE TITLE
Crash when breaking a Refined Pipe. 

### ISSUE THREAD

**Issue by Radagast** [DarkPacks/SkyFactory-One#27]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.0

### Java version

1.8.0_202, Oracle Corporation

### Modpack Launcher Used

ATLauncher

### Memory Allocated

6GB

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

Breaking a refined pipe with an iron pickaxe. The first hit the game crashed - See crash report. Also game will not restart. See Second crash report. I need to check if this needs a reinstall or the instance.

OS Linux - openSUSE Tumbleweed. Java is supplied by the launcher. 

**EDIT** I was able to restart the game after restarting the launcher.

**Important** The crash is repeatable. Hit a pipe and crash. I changed the option at the top.

### Additional Information

Refined Pipe Crash - https://pastebin.com/h3sQiiM9

Crash trying to open the game after the refined pipe crash - https://pastebin.com/PqtAV3fL

**Comment by klugemonkey** [comment]
FYI,
Looks like bug was fixed in March (7 months ago) but an updated mod was never posted to CurseForge.  
Version 0.5.1+8 seems to fix the issue and is available on their ci site: https://ci.refinedmods.com/job/refinedpipes-mc1.16/

**Comment by Darkosto** [comment]
A modpack update went out on Thursday with a fix for this bug. CureForge is incredibly slow and not approved it yet. The update is available right now on ATLauncher
