### ISSUE TITLE
[Bug]: TiCo Force Furnace Dupe

### ISSUE THREAD

**Issue by DunYeeted** [DarkPacks/SkyFactory-One#29]
### General Info

- [x] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.0

### Java version

Java 8 Update 51

### Modpack Launcher Used

Curseforge Launcher

### Memory Allocated

4GB

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

**Steps:**

1. Get a Tinkers' Construct **Crafting Station**
2. Get a ForceCraft **Force Furnace (Any color will work)** 
3. Get at least two of the item you want to dupe (Only works with items that stack)
4. Open crafting station and under where it says "Force Furnace" (The text will overlap), place an item in the fourth slot
5. Open the force furnace and attempt to take out the items
6. It will give you one less than the amount of items in the slot
7. The items will remain inside the slot
        7a. If you are holding the same items as are in the slot it will also add those to the stack
Repeat steps 5-7

### Additional Information

https://user-images.githubusercontent.com/75920735/137228210-77eb7a74-7202-492a-9c54-fe67b01975fd.mp4

Unknown (but presumed to work) in multiplayer modes

**Comment by DunYeeted** [comment]
Forgot to mention, but yes I did test in survival and the same occured

**Comment by Darkosto** [comment]
Will be fixed in ForceCraft in the next pack update (1.0.1)
