### ISSUE TITLE
[Suggestion]: OreExcavation - increase "range" to 32

### ISSUE THREAD

**Issue by grannymc** [DarkPacks/SkyFactory-One#33]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Range (distance excavation can travel) is set to 20, which is too small for the tallest 2x2 spruce and jungle trees. Suggest increasing to 32.

**Comment by Darkosto** [comment]
Will consider, FYI this has been matched to the original pack: 

`limit {
    # Limit of blocks to be destroyed at once. Use -1 for infinite. [range: -1 to 2147483647, default: '800']
    I:limit.blocks=800

    # Maximum number of blocks to be removed per game tick (1/20 seconds). Using a low number will keep the game from getting huge performance drops but also decreases the speed at which blocks are destroyed. [range: 1 ~ 1000, default: 10]
    I:limit.blocksPerTick=10

    # Maximum distance from the first block to search for blocks to destroy. [range: -1 to 1000, default: '20]
    I:limit.radius=20
}
`
