### ISSUE TITLE
[Bug]: Ender Inhibitor does not affect Ender Slimes

### ISSUE THREAD

**Issue by ZeroLyfe** [DarkPacks/SkyFactory-One#35]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.0

### Java version

Java 8 update 301 64bit

### Modpack Launcher Used

MultiMc

### Memory Allocated

12gb

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

The Mob Grinding Utilities Ender Inhibitor is not stopping Tinkers Ender Slimes from teleporting out of my mob farm or from teleporting me when they hit me. I have placed the inhibitors all over my base to try and prevent this but theses slimes are just griefing me when my mob farm is on.

**Comment by Darkosto** [comment]
Fixed and will be out with the 1.0.3 pack update
