### ISSUE TITLE
Witch spawn rate/self-healing speed seems high

### ISSUE THREAD

**Issue by exist2subsist** [DarkPacks/SkyFactory-One#43]
I built a mob farm using a 3x3 drop chute 20 blocks high and the spawn rooms are 8x8x2 (8 spawn rooms total), the witch spawn rate seems so much higher than any other mob as well they are more difficult to kill than normal (self-healing?). Not sure if this is by design but I don't recall this in the original SF1 pack and doesn't occur in vanilla 1.16.5 so figured I would check. Thanks for the pack!

![2021-10-15_09 14 43](https://user-images.githubusercontent.com/51752471/137506794-fdef72a6-8700-43b1-9b56-3d188a2996ad.png)

**Comment by Gremkow** [comment]
@klugemonkey So I still think witches spawn pretty often, but what you are describing is also partially true.
Cyclic Diamond Spikes are not weak tho, it looks like they bug out after some time (for me on SMP).

For player kills they seem to simulate a sword swipe (as it is audible and you can see the particle/animation). After some time they simply stop working. They still react to redstone (spikes (de)activating) but dont hurt _anything_ anymore. Only replacing them fixes this.

**Comment by Gremkow** [comment]
@Darkosto I experienced this in version 1.0.0
I have played a couple of hours in 1.0.1 and did not come across unusual numbers of witches yet.

I think the original post was before 1.0.1 was released?

**Comment by exist2subsist** [comment]
> Witch spawn rates were altered in the 1.0.1 version of the pack. We ask that you fill out issue templates so that we can confirm what version you're running. Issues like these are hard to track down when I don't have the relevant information, please add it so I don't have to spend time trying to replicate the issue in an open environment

Apologies, yes I was playing version 1.0.0 when I noticed this. I have updated to 1.0.1 and it seems improved. Haven't posted something like this before, sorry for not including more relevant information - will keep that in mind before opening anything in future. Thanks!
