### ISSUE TITLE
[Bug]: cyclic fluid pipes don't drop filter card when broken

### ISSUE THREAD

**Issue by innesm** [DarkPacks/SkyFactory-One#44]
### General Info

- [x] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.0

### Java version

1.8.0_51 64 bit

### Modpack Launcher Used

Curseforge Launcher

### Memory Allocated

7 GB

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

What happened:
Holding a filter card, right click to open the UI, place a bucket of fluid in it to set the filter. Place a fluid pipe, use the wrench to configure one end as output, then right click without the wrench to insert the filter card. 
Break the pipe - you don't get the card or its contents back.

What I expected: 
The filter card, still containing the bucket, would drop when the pipe was broken.

**Comment by Darkosto** [comment]
This is an issue with Cyclic, not the modpack. This needs to be reported to the developer of Cyclic. I cannot do anything to change this within the pack: https://github.com/Lothrazar/Cyclic/issues
