### ISSUE TITLE
[JEI/Item search] When searching uses for "apple", Culinary generator is blank for use, shows up in Culinary generator.

### ISSUE THREAD

**Issue by Demlou6** [DarkPacks/SkyFactory-One#5]
When searching for uses of apples, I wanted to see how much RF an Apple was worth in the Culinary generator by clicking on the generator tab, see:

![image](https://user-images.githubusercontent.com/39318317/120083715-43c8f880-c090-11eb-85f9-53bc80e87d1d.png)

When you click the tab you see this:

![image](https://user-images.githubusercontent.com/39318317/120083720-4b889d00-c090-11eb-8487-0da6ef8ede7b.png)

When you go specifically to the generator tabs, and see what can be used with Culinary generator you can find apple, see:

![image](https://user-images.githubusercontent.com/39318317/120083732-61965d80-c090-11eb-853a-3b15b4178d06.png)

**Comment by Demlou6** [comment]
This seems to apply to all food items in the culinary generator when seeing its "use" by using the 'u' key and selecting that generator tab.

**Comment by Darkosto** [comment]
Finally fixed!
