### ISSUE TITLE
[Suggestion]: server 1.0.1

### ISSUE THREAD

**Issue by marindumont** [DarkPacks/SkyFactory-One#52]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

hello, 
great staff !
Can you update the modpack for the server side also?
Regards

**Comment by sam-kirby** [comment]
This is currently awaiting approval and has been for several days; there is nothing we can do to speed this up.
