### ISSUE TITLE
[Bug]: Gamerules and world spawn reset when multiplayer server restarts

### ISSUE THREAD

**Issue by TheDeviantCrafter** [DarkPacks/SkyFactory-One#53]
### General Info

- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Modpack version

1.0.0

### Java version

Java 8 update 301

### Modpack Launcher Used

GDLauncher

### Memory Allocated

4 GB

### Minecraft World Environment

Server

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Server Java Version

Java 8 update 301

### Server Operating System

Windows 10

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

Each time the server restarts, gamerules and the /setworldspawn location resets to their default values. Changes made to these commands only persist until the next restart. Until then they work as expected.

### Additional Information

Have not tested in singleplayer or in version 1.0.1. Waiting on an official server download before I update.

**Comment by artdude543** [comment]
Hello!

We are looking into this issue more with the developer of the mod and ourselves with more testing/reviewing. We'll update you here once we have anything in regards. But, we are 100% aware of this issue and working on it as quickly as possible.

Thanks!
