### ISSUE TITLE
[Bug]: Slime Chunk reset

### ISSUE THREAD

**Issue by ShyNieke** [DarkPacks/SkyFactory-One#60]
### General Info

- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.1

### Java version

Java 8 Update 252

### Modpack Launcher Used

GD Launcher

### Memory Allocated

8 GB

### Minecraft World Environment

Server

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Server Java Version

Java 11.0.9.1

### Server Operating System

Unsure (Akliz is the server host)

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

Whenever the server reboots slime chunks get randomised, meaning what once was a slime chunk has a chance to no longer being a slimechunk. this is not a visual bug as one day my mob farm generates slimes and the next day it won't spawn a single slime.

Server restarts daily for stability reasons

**Comment by mjwells2002** [comment]
After updating to java 11.0.12 and changing nothing else on modpack version 1.0.0 the seed does not change but the logs seem to be the same https://bin.bloom.host/ocomejuxev
