### ISSUE TITLE
[Suggestion / Maybe bug?]: Add Campfire to list of Crucible Heat Sources.

### ISSUE THREAD

**Issue by piisawheel** [DarkPacks/SkyFactory-One#75]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Seems odd to omit this one when clearly that's what it's for.

**Comment by sam-kirby** [comment]
The way heat is currently implemented in ENS does not allow the crucible to distinguish between a lit campfire and an unlit one.
