### ISSUE TITLE
[Suggestion]: Addition of NoMoWanderer as a way of preventing Wandering Trader spawns

### ISSUE THREAD

**Issue by tyreforhyred** [DarkPacks/SkyFactory-One#80]
### General Info

- [X] I would like to propose new content
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

While it's nice getting free leads from uhh removing the wandering trader/llamas that periodically spawns it would also be nice to remove their ability to spawn when you aren't seeking out their trades. Looking at Torchmaster's code and issues page it seems the Dread Lamp is not currently able to block the spawns of Wandering Traders, else I would just be using that.  
Link to the relevant mod: [NoMoWanderer](https://www.curseforge.com/minecraft/mc-mods/nomowanderer).

**Comment by Darkosto** [comment]
I don't know why I would block the wandering traders, I've kept them in the pack purposely. I don't have an intention of removing them.

Thanks for the suggestion!

**Comment by grannymc** [comment]
Wandering Trader spawns can be disabled with "/gamerule doTraderSpawn false". This option is also available at world creation through the Game Rules button on the world creation screen.
