### ISSUE TITLE
[Bug]: Void Topography World Spawn

### ISSUE THREAD

**Issue by GraidG** [DarkPacks/SkyFactory-One#83]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.1

### Java version

Java 8 , Update 301

### Modpack Launcher Used

MultiMC

### Memory Allocated

5GB

### Minecraft World Environment

Single Player

### Misc Client Info

- [X] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

Whenever I create topography world it just spawns me in the void. no tree, no island, nothing, and then I just die ! I need help in world generation stuff Plz help... There are no other problems such as crashes or anything..

### Additional Information

Plz contact me on My discord : GraidG#5908

**Comment by Armed-Mob** [comment]
So I did not start this thread but we are working on a server for a twitch community and having the spawn randomly change.  linked is the latest server log.

We also did setworldspawn 2 65 2 and that did get him to spawn but the first 2 players loaded in fine.

https://filebin.net/1znj9zj4gm1jaxnz

**Comment by Darkosto** [comment]
@Armed-Mob This thread is a different issue than you are experiencing. We have already discovered and addressed the issue in dev and answered on this issue: https://github.com/DarkPacks/SkyFactory-One/issues/60 & https://github.com/DarkPacks/SkyFactory-One/issues/54 & https://github.com/DarkPacks/SkyFactory-One/issues/53

As of right now, the mod that had to fix this is not yet public so we cannot push a pack update until then.

**Comment by Armed-Mob** [comment]
@Darkosto Thanks, Been scouring the internet trying to find something.  I briefly looked at the closed tickets but not in-depth.  Sorry for the inconvenience and thanks for the update again!

**Comment by Darkosto** [comment]
@Armed-Mob No worries and definitely not an inconvenience!
