### ISSUE TITLE
[ex nihilo sequentia] crucible heat sources Jei listings

### ISSUE THREAD

**Issue by sunsetwhiskey** [DarkPacks/SkyFactory-One#9]
on the heat sources jei listing page:
"flint and steel" is listed twice on page 2 one at 6x one at 4x.
torch is listed twice, once on page 1 and once on page 2. Both those heat sources list 2x

![crucible](https://user-images.githubusercontent.com/32500058/127754343-45ab38bd-522b-45d2-8949-03e486bf8914.PNG)

**Comment by Darkosto** [comment]
Yep. This is a limitation of the Ex Nihilo devs. They don't know how to add an icon for Fire so they made the image flint and steel. I cannot fix this. It's on them to figure out how to show fire properly
