### ISSUE TITLE
[Bug]:  cyclic gps card

### ISSUE THREAD

**Issue by wolfdances** [DarkPacks/SkyFactory-One#94]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.2

### Java version

1.16.5

### Modpack Launcher Used

CurseForge Launcher

### Memory Allocated

7gb

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

previous version when using cyclic gps card to link block for wireless senders, use to click and highlight the block you wanted.  but todays update it highlights the block next to what you want to click making linking dificult.  you now have to break the machine or block, link the area with gps card, then put machine back in area you just highlighted.

**Comment by willrun4fun** [comment]
I'm running 1.5.8 and the highlighted block still does not line up when crouching.

**Comment by Darkosto** [comment]
Just checked 1.5.8 for myself and everything functioned properly. If anyone has follow up on this let me know.

**Comment by willrun4fun** [comment]
I figured it out.  I was flying and used Shift+Space to right click.  If I'm standing on the ground the GPS works correctly.

**Comment by Zizes** [comment]
I have same problem with machine blocks. For example, if I want to send wireless energy to forester I have to break forester machine and use cyclic gps card with shift + right click on block that would be near the forester. I couldn't use gps card using just right click because it opens forester GUI.

**Comment by Darkosto** [comment]
This is fixed and will be available in the new pack version (1.0.3)
