### ISSUE TITLE
[Bug]: Absorption hopper no longer working

### ISSUE THREAD

**Issue by NotPiffany** [DarkPacks/SkyFactory-One#95]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.2

### Java version

Java 8 update 231

### Modpack Launcher Used

GD Launcher

### Memory Allocated

10 GB

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

After I updated yesterday, the absorption hoppers from Mob Grinding Utils stopped working. This applies to ones placed both before and after the update.

**Comment by Darkosto** [comment]
Looks like we can close this, it's probably a side effect of the pack update.
