### ISSUE TITLE
[Bug]: Infinite Energy

### ISSUE THREAD

**Issue by ZorlicX** [DarkPacks/SkyFactory-One#97]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.2

### Java version

Java 1.8.0.51 (64 Bit)

### Modpack Launcher Used

CurseForge

### Memory Allocated

8 GB

### Minecraft World Environment

Single Player

### Misc Client Info

- [X] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

Placing a Geothermal Generator from simple generators next to a Redstone Flux Cell from Thermal Series allows for infinite energy. Simply allow for auto-input on the RF Cell and select the side of the cell the generator is on and it starts creating power. No lava is ever needed, not even to jump start the system. You can surround a cell with 4 or 5 of the generators and then add a Resonant Integral Component, an Expanded RF Coil and a High-Flux RF Coil to generate roughly 24k a tick per generator. Works with any Simple Generator generator.

**Comment by PocketRug** [comment]
the same thing happens with energy cables from cyclic, however, the cable will be left with a negative amount of energy near the integer limit. You can imagine my confusion when my power grid whent offline

**Comment by Darkosto** [comment]
ValkyrieLib just updated to fix this issue. Should be in the next modpack update. Thanks!
