### ISSUE TITLE
[Bug]: Crystallised amber disappears from solidification chamber/inventory

### ISSUE THREAD

**Issue by PaternoX** [DarkPacks/SkyFactory-One#99]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.2

### Java version

java 8 update 51

### Modpack Launcher Used

curseforge launcher

### Memory Allocated

8 GB

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

when crafting crystallised amber in the solidification chamber, when you click on the amber it disappears, and the raw items (fire charge, redstone block and gold - but not the liquid magma) go back into the input slots.

If you shift-click the amber into your inventory, when you close and then reopen your inventory the amber disappears, and the raw items are again back in the solidification chamber.

**Comment by Darkosto** [comment]
This is a visual error only, and is only replicatable for me when I click too fast before the item is in the output slot. Technically, this is a Cyclic bug and not a pack bug. I'm going to close this though as it's something we need to worry about.
